# Database Configuration for Amazon RDS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.com.reliefcircle=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.LazyInitializationException=ERROR
logging.level.com.amazonaws=DEBUG

# Okta Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-123456.okta.com/oauth2/default
spring.security.oauth2.resourceserver.jwt.audience=api://default

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
logging.level.org.springframework.security=DEBUG

# PayPal Configuration
paypal.client.id=your-client-id-here
paypal.client.secret=your-client-secret-here
paypal.mode=sandbox

# AWS Configuration
cloud.aws.sns.endpoint=https://sns.us-east-2.amazonaws.com
cloudfront.url=${CLOUDFRONT_URL}
cloudfront.id=${CLOUDFRONT_ID}
sns.topic.arn=${SNS_TOPIC_ARN}
aws.accesskeyid=${aws.accessKeyId}
aws.secretkey=${aws.secretkey}
aws.accessKeyId=${aws.accessKeyId}
aws.secretKey=${aws.secretkey}
aws.region=us-east-2


# S3 Bucket for uploading proof documents by charities
aws.s3.bucket-name=reliefcircles3
aws.s3.endpoint=https://s3.us-east-2.amazonaws.com
cloud.aws.region.static=us-east-2
cloud.aws.stack.auto=false

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000




